name: Build and Test

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: install test
    steps:
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.2.1
        with:
          version: 7.4.3663
      - name: Tag repo
        uses: changesets/action@1
        if: ${{ github.ref == 'refs/heads/main' && startsWith(github.event.commits[0].message, 'Version Packages') }}
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}